theme: minima
title: Data Analysis Projects
author: Kennedi Neri
description: Feel free to contact me via LinkedIn or at my personal email address: kennedi.neri@gmail.com. My LinkedIn is accessible here: https://www.linkedin.com/in/kennedineri/. 

