remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: Data Analysis Projects
author: Kennedi Neri
description: Project portfolio page using various data analysis tool including SQL, Python, and R.

collections:
  posts:
    output: true
    permalink: /blog/:title/
